### ISSUE TITLE
error message from openqa-review

### ISSUE THREAD

**Issue by yxususe** [okurz/openqa_review#72]
Output will be attached.

**Comment by yxususe** [comment]
Here is the link of openqa-review output:
https://w3.suse.de/~yxu/openqa-review-output

**Comment by okurz** [comment]
@yxususe The problem is that your argument to '-j' is not specific enough ending up in trying to compare two builds within the released SLE 12 HA group which does not work.

See the log output:

```
INFO:openqa_review.openqa_review:Job group URL for Functional: {u'SLE 15 / Functional': 'https://openqa.suse.de/group_overview/110', u'Released / SLE 12 SP3 Functional: Server': 'https://openqa.suse.de/group_overview/55', u'Released / SLE 12 SP3 Functional: Desktop': 'https://openqa.suse.de/group_overview/61', u'Released / SLE 12 SP3 Functional: HA': 'https://openqa.suse.de/group_overview/64'}
[…]
DEBUG:openqa_review.openqa_review:Comparing specified build 173.8 against last reviewed 0290
```

This is not what you want. You wanted `-j Functional` to match only on the first. Try `-j 'SLE.*/ Functional'` or `-J https://openqa.suse.de/group_overview/110` to be specific.
